### ISSUE TITLE
Adding pre-render to any page breaks builds handleHttpError

### ISSUE THREAD

**Issue by BradNut** [Rykuno/TofuStack#3]
In a clean slate clone, adding a new page such as "docs" or "about" and setting the +page.ts to pre-render causes an `handleHttpError` to be thrown on a regular build.

### Steps to reproduce

1. Clone the repository
2. Install node v22 from nvm, `nvm install v22`, as of writing this installs v22.5.1 and not v22.1.0 as the `.node-version` states
3. Run `pnpm install`
4. Run `pnpm initialize`
5. Add a route of `docs` under `routes/(app)`
6. Add a +page.svelte with code: `<h1>Testing</h1>`
7. Add a +page.ts with code:
```typescript
import { dev } from '$app/environment';

export const csr = dev;

export const prerender = true;
```
8. Run `pnpm build`
9. See the error

Have you run into this or is there any good workaround?

### Error
```
Error: Cannot read clientAddress during prerendering
    at Object.getClientAddress (file:///{directory}/Sveltekit-TaroStack/node_modules/.pnpm/@sveltejs+kit@2.5.17_@sveltejs+vite-plugin-svelte@3.1.1_svelte@5.0.0-next.164_vite@5.3.1_@typ_vdl2priufhva2prhl63tf6nkdq/node_modules/@sveltejs/kit/src/core/postbuild/prerender.js:204:11)
    at apiClient (file:///{directory}/Sveltekit-TaroStack/.svelte-kit/output/server/chunks/hooks.server.js:56:32)
    at apply_handle (file:///{directory}/Sveltekit-TaroStack/.svelte-kit/output/server/chunks/hooks.server.js:12:14)
    at Object.handle (file:///{directory}/Sveltekit-TaroStack/.svelte-kit/output/server/chunks/hooks.server.js:9:12)
    at respond (file:///{directory}/Sveltekit-TaroStack/.svelte-kit/output/server/index.js:3083:43)
    at async visit (file:///{directory}/Sveltekit-TaroStack/node_modules/.pnpm/@sveltejs+kit@2.5.17_@sveltejs+vite-plugin-svelte@3.1.1_svelte@5.0.0-next.164_vite@5.3.1_@typ_vdl2priufhva2prhl63tf6nkdq/node_modules/@sveltejs/kit/src/core/postbuild/prerender.js:202:20)

node:internal/event_target:1090
  process.nextTick(() => { throw err; });
                           ^
Error: 500 /docs
To suppress or handle this error, implement `handleHttpError` in https://kit.svelte.dev/docs/configuration#prerender
    at file:///{directory}/Sveltekit-TaroStack/node_modules/.pnpm/@sveltejs+kit@2.5.17_@sveltejs+vite-plugin-svelte@3.1.1_svelte@5.0.0-next.164_vite@5.3.1_@typ_vdl2priufhva2prhl63tf6nkdq/node_modules/@sveltejs/kit/src/core/config/options.js:202:13
    at file:///{directory}/Sveltekit-TaroStack/node_modules/.pnpm/@sveltejs+kit@2.5.17_@sveltejs+vite-plugin-svelte@3.1.1_svelte@5.0.0-next.164_vite@5.3.1_@typ_vdl2priufhva2prhl63tf6nkdq/node_modules/@sveltejs/kit/src/core/postbuild/prerender.js:65:25
    at save (file:///{directory}/Sveltekit-TaroStack/node_modules/.pnpm/@sveltejs+kit@2.5.17_@sveltejs+vite-plugin-svelte@3.1.1_svelte@5.0.0-next.164_vite@5.3.1_@typ_vdl2priufhva2prhl63tf6nkdq/node_modules/@sveltejs/kit/src/core/postbuild/prerender.js:413:4)
    at visit (file:///{directory}/Sveltekit-TaroStack/node_modules/.pnpm/@sveltejs+kit@2.5.17_@sveltejs+vite-plugin-svelte@3.1.1_svelte@5.0.0-next.164_vite@5.3.1_@typ_vdl2priufhva2prhl63tf6nkdq/node_modules/@sveltejs/kit/src/core/postbuild/prerender.js:236:3)

Node.js v22.5.1
 ELIFECYCLE  Command failed with exit code 1.
```

**Comment by BradNut** [comment]
I believe the issue here is that in the `hooks.server.ts` file, if you want to have pre-rendered pages, you cannot check the `event.getClientAddress()` or at least you need to have some condition to not do it for pre-render SvelteKit builds.

Current code:
```typescript
const { api } = hc<ApiRoutes>('/', {
  fetch: event.fetch,
  headers: {
	'x-forwarded-for': event.getClientAddress(),
	host: event.request.headers.get('host') || ''
  }
});
```

Working code (if you remove it):
```typescript
const { api } = hc<ApiRoutes>('/', {
  fetch: event.fetch,
  headers: {
	host: event.request.headers.get('host') || ''
  }
});
```

**Comment by BradNut** [comment]
However, another thing I noticed is that I cannot use `'@sveltejs/adapter-vercel'` with this project. I have to use `'@sveltejs/adapter-node'` or I get:
```
> Using @sveltejs/adapter-vercel
glob error [Error: EACCES: permission denied, scandir '/run/user/1000/systemd/inaccessible/dir'] {
  errno: -13,
  code: 'EACCES',
  syscall: 'scandir',
  path: '/run/user/1000/systemd/inaccessible/dir'
}
error during build:
Error: EACCES: permission denied, scandir '/run/user/1000/systemd/inaccessible/dir'
 ELIFECYCLE  Command failed with exit code 1.
 ```
 
 Is there a specific reason we need to use the node adapter @Rykuno?

**Comment by Rykuno** [comment]
Hey sry, I havent been working on this repo too much as I have a private repo in the works that has large improvements, simplification, and actual docs and guides. 

The new build should work with serveless adapters, but its largely designed to be a one click deploy to a dedicated VMS. Ideally we do not use the `x-forwarded-for` header as its only present for rate limiting and as we all know, rate limiting based on IP is not really a great way to do things.

I've switched to anonymous sessions and tracking rate limiting through those. It has extremely little overhead and is much more accurate as we can now track browser sessions too. All of these features are based on personal needs but im happy to accept improvements.

**Comment by Rykuno** [comment]
To clarify, ATM. the `event.getClientAddress()` I believe is only suppored through the node adapter for sveltekit https://kit.svelte.dev/docs/adapter-node.

**Comment by BradNut** [comment]
@Rykuno, no problem! It makes sense but thank you for responding and updating the public version. It would he cool to see how you're implementing the anonymous session tracking if you have the time to add it here.

I'll take a look at all the updates and client address only available through node makes sense. Just wanted to raise this for clarification.
