### ISSUE TITLE
Unexpected character '\u{7f}' on pnpm build

### ISSUE THREAD

**Issue by BradNut** [Rykuno/TofuStack#4]
In a clean slate clone, running `pnpm build` fails with `Unexpected character '\u{7f}'`.

### Steps to reproduce

1. Clone the repository
2. Install node v22 from nvm, `nvm install v22`, as of writing this installs v22.5.1 and not v22.1.0 as the `.node-version` states
3. Run `pnpm install`
4. Run `pnpm initialize`
5. Run `pnpm build`
6. See the error

### Error

```
Run npm run preview to preview your production build locally.

> Using @sveltejs/adapter-node
[ioredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:6379
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1605:16)
[ioredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:6379
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1605:16)
[ioredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:6379
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1605:16)
[ioredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:6379
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1605:16)
[ioredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:6379
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1605:16)
[ioredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:6379
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1605:16)
undefined
/{directory}/projects/Sveltekit-TaroStack/node_modules/.pnpm/@node-rs+bcrypt-linux-x64-gnu@1.9.0/node_modules/@node-rs/bcrypt-linux-x64-gnu/bcrypt.linux-x64-gnu.node
error during build:
RollupError: Unexpected character '\u{7f}'
    at getRollupError (file:///{directory}/projects/Sveltekit-TaroStack/node_modules/.pnpm/rollup@4.17.0/node_modules/rollup/dist/es/shared/parseAst.js:396:41)
    at ParseError.initialise (file:///{directory}/projects/Sveltekit-TaroStack/node_modules/.pnpm/rollup@4.17.0/node_modules/rollup/dist/es/shared/node-entry.js:11333:28)
    at convertNode (file:///{directory}/projects/Sveltekit-TaroStack/node_modules/.pnpm/rollup@4.17.0/node_modules/rollup/dist/es/shared/node-entry.js:13087:10)
    at convertProgram (file:///{directory}/projects/Sveltekit-TaroStack/node_modules/.pnpm/rollup@4.17.0/node_modules/rollup/dist/es/shared/node-entry.js:12404:12)
    at Module.setSource (file:///{directory}/projects/Sveltekit-TaroStack/node_modules/.pnpm/rollup@4.17.0/node_modules/rollup/dist/es/shared/node-entry.js:14248:24)
    at async ModuleLoader.addModuleSource (file:///{directory}/projects/Sveltekit-TaroStack/node_modules/.pnpm/rollup@4.17.0/node_modules/rollup/dist/es/shared/node-entry.js:18901:13)
 ELIFECYCLE  Command failed with exit code 1.
```

**Comment by BradNut** [comment]
It seems that moving the `oslo` dependency from `devDependencies` to the regular `dependencies` fixes this issue. Do you also find that this is true @Rykuno?

**Comment by maietta** [comment]
@BradNut, it is indeed true that Osla is a regular dependency, not a dev dependency, per the docs:

https://github.com/pilcrowOnPaper/oslo

**Comment by BradNut** [comment]
@maietta, yeah I found that after. Thank you!

But overall I guess it's good if people see this and have the same issue. Would be good to get it updated on this if people try to fork or use it. Otherwise I'll close this.

**Comment by Rykuno** [comment]
@BradNut Again sry, this is fixed in a private repo I'm working on. 

https://github.com/Rykuno/Sveltekit-TaroStack/blob/main/src/lib/server/api/services/hashing.service.ts

Its indeed an issue with Aargon2 which oslo implements. To get around this issue I've taken the Scrypt crpyto library and its best configs from Oslo and implemented it in the `hashing.service.ts`. This fixes the issue.

**Comment by BradNut** [comment]
@Rykuno , makes sense. For now I've added the Oslo dependency as a regular dependency since I was at to use Argo2 for now. Thank you for updating the repository though! 🙂
